######################################################################
# Automatically generated by qmake (1.04a) Wed Jun 16 17:00:37 2004
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += slicing_flrpln polygon gpolygon segment zonotope

