function [c,ceq]=optInvcon(p_fall,p_rise,width)
%    ceq = [fitgp_fall(p_fall,width(1),width(2)) -...
%           fitgp_rise(p_rise,width(1),width(2))];
    ceq = [];
    c = [...
        width(1) + width(2) - 10;
        fitgp_fall(p_fall,width(1),width(2))/...
        fitgp_rise(p_rise,width(1),width(2))-1.001;
        0.999 - fitgp_fall(p_fall,width(1),width(2))/...
        fitgp_rise(p_rise,width(1),width(2));
        ];
