######################################################################
# Automatically generated by qmake (1.07a) Sat Dec 2 15:48:38 2006
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += example1.cpp example2.cpp example3.cpp example4.cpp example5.cpp
